name: Mend Image Scan

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name'
        required: true
        default: 'my-app:latest'
      product:
        description: 'Product name'
        required: true
        default: 'local-dev'
      project:
        description: 'Project name'
        required: true
        default: 'my-app'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Mend CLI
        run: |
          curl -L https://downloads.mend.io/cli-standalone/mend_linux_amd64.tgz -o mend.tgz
          tar -xvzf mend.tgz
          sudo mv mend /usr/local/bin/mend
          chmod +x /usr/local/bin/mend

      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.image_name }} .

      - name: Scan Docker Image
        run: |
          mend image "${{ inputs.image_name }}" \
            --product "${{ inputs.product }}" \
            --project "${{ inputs.project }}"

